### ISSUE TITLE
Problem with "\n" when parsing

### ISSUE THREAD

**Issue by guillecledou** [ReoLanguage/ReoLive#1]
(\x.fifo^x) ; 
(\n.drain^n) 

Error:
Parser failure: [1.15] failure: string matching regex `[a-z][a-zA-Z0-9_]*' expected but `\' found
(\x.fifo^x) ; \n(\n.drain^n)
^

**Comment by joseproenca** [comment]
Encoding problem only in the server version. Now solved.
